## HW #2

In [1]:
import numpy
import os
water_file = os.path.join('data','water.xyz')

water_coordinates = numpy.genfromtxt(fname=water_file, delimiter='',skip_header=2,dtype='unicode')
print(water_coordinates)

[['O' '0.000000' '-0.007156' '0.965491']
 ['H1' '-0.000000' '0.001486' '-0.003471']
 ['H2' '0.000000' '0.931026' '1.207929']]


In [2]:
atoms=water_coordinates[:,1:]
print(atoms)

[['0.000000' '-0.007156' '0.965491']
 ['-0.000000' '0.001486' '-0.003471']
 ['0.000000' '0.931026' '1.207929']]


In [3]:
atom_headers= water_coordinates[:,:1]
print(atom_headers[0])


['O']


In [4]:
atoms = atoms.astype(numpy.float)
print(atoms)

[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]


In [5]:
num_columns = len(atom_headers)
print(num_columns)

3


In [8]:
#Looking for distances among all atoms

for i in range(0,num_columns):
    for j in range(0,num_columns):
        x_coord= (atoms[i,0]-atoms[j,0])**2
        y_coord= (atoms[i,1]-atoms[j,1])**2
        z_coord= (atoms[i,2]-atoms[j,2])**2
        distance=numpy.sqrt(x_coord+y_coord+z_coord)
        print(F'{atom_headers[i]} to {atom_headers[j]}:{distance:.3f}')
        

   

['O'] to ['O']:0.000
['O'] to ['H1']:0.969
['O'] to ['H2']:0.969
['H1'] to ['O']:0.969
['H1'] to ['H1']:0.000
['H1'] to ['H2']:1.527
['H2'] to ['O']:0.969
['H2'] to ['H1']:1.527
['H2'] to ['H2']:0.000
